build stage:  
   image: doctrine/nodejs-aws-cli:v10.19
   stage: build  
   only:    
      - staging  
   script:
      - export BACKEND_URL_ECS=$(aws ssm get-parameter --name "backend_url_ecs" --query "Parameter.Value" --output text --region "us-east-1")
      - echo $BACKEND_URL_ECS
      - sed -i "s/backend_url/$BACKEND_URL_ECS/" src/environments/environment.ts
      - sed -i "s/backend_url/$BACKEND_URL_ECS/" src/environments/environment.prod.ts    
      - npm install --save --legacy-peer-deps    
      # Build App    
      - npm run build 
   artifacts:    
      paths:      
         # Build folder      
         - dist/    
      expire_in: 1 hour

deploy stage:  
   image: python:latest  
   stage: deploy  
   only:    
      - staging  
   script:    
      - pip install awscli    
      - aws s3 sync ./dist/webapp/ s3://stage.codingbc-sandbox.com   
